runtime: php55
api_version: 1

# env_variables:
#     # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
#     # values obtained when configuring your Cloud SQL instance.
#     MYSQL_USER: root
#     MYSQL_PASSWORD: 411
#     MYSQL_DSN: mysql:dbname=partier;unix_socket=/cloudsql/partier-202001:us-east4:event-planner

handlers:

# Serve php scripts
- url: /
  script: index.php

- url: /index.php
  script: index.php

- url: /event.php
  script: event.php

- url: /create.php
  script: create.php

- url: /verify.php
  script: verify.php

# Serve files
- url: /styles.css
  static_files: styles.css
  upload: styles.css

- url: /images/back.png
  static_files: images/back.png
  upload: images/back.png

- url: /images/favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /pacifico.ttf
  static_files: pacifico.ttf
  upload: pacifico.ttf

- url: /PoiretOne.ttf
  static_files: PoiretOne.ttf
  upload: PoiretOne.ttf
